# Generated by Django 2.0.4 on 2018-04-05 07:52

from django.db import migrations, models
import files.helps


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=files.helps.get_file_path)),
                ('media_type', models.IntegerField(choices=[(1, 'Video'), (2, 'Url')], default=1)),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('show_name', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
