# Generated by Django 2.0.4 on 2018-04-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(blank=True)),
                ('time_ended', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('media_type', models.IntegerField(choices=[(1, 'Video'), (2, 'Url')], default=1)),
                ('type_os', models.IntegerField(choices=[(1, 'Android'), (2, 'IOS')], default=1)),
                ('is_show_name', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StimulusConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.IntegerField(choices=[(1, 'AR'), (2, 'VR')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='files',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.RemoveField(
            model_name='files',
            name='show_name',
        ),
        migrations.AddField(
            model_name='stimulusconfiguration',
            name='files',
            field=models.ManyToManyField(related_name='files_list', to='files.Files'),
        ),
        migrations.AddField(
            model_name='questionnaireconfiguration',
            name='stimulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulus_questionnaires', to='files.StimulusConfiguration'),
        ),
        migrations.AddField(
            model_name='datatrack',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_datatracks', to='files.QuestionnaireConfiguration'),
        ),
        migrations.AddField(
            model_name='datatrack',
            name='stimulus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stimulus_datatracks', to='files.StimulusConfiguration'),
        ),
    ]
