# Generated by Django 2.0.4 on 2018-04-23 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180415_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_configurations', to='files.FileConfiguration'),
        ),
    ]
