# Generated by Django 2.0.4 on 2018-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_files_file_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.RemoveField(
            model_name='files',
            name='url',
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileconfiguration',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'Video'), (2, 'ASSETBUNDLE')], default=1),
        ),
    ]
