# Generated by Django 2.0.4 on 2018-06-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180425_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulusconfiguration',
            name='type_os',
            field=models.IntegerField(choices=[(1, 'Android'), (2, 'IOS')], default=1),
        ),
        migrations.AlterField(
            model_name='datatrack',
            name='time_ended',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datatrack',
            name='time_started',
            field=models.DateTimeField(),
        ),
    ]
