# Generated by Django 2.0.4 on 2018-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20180608_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulusconfiguration',
            name='android_files',
            field=models.ManyToManyField(blank=True, limit_choices_to={'file_configuration__type_os': 1}, null=True, related_name='files_android_list', to='files.Files'),
        ),
        migrations.AlterField(
            model_name='stimulusconfiguration',
            name='ios_files',
            field=models.ManyToManyField(blank=True, limit_choices_to={'file_configuration__type_os': 2}, null=True, related_name='files_ios_list', to='files.Files'),
        ),
    ]
