# Generated by Django 2.0.4 on 2018-10-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20180608_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaireconfiguration',
            options={'verbose_name': 'Stimuluи Instance (SA)', 'verbose_name_plural': 'Stimulus Instance (SA)'},
        ),
        migrations.RemoveField(
            model_name='fileconfiguration',
            name='is_show_name',
        ),
    ]
